{
  "hash": "9405dc9e90bc9498a05463fd1bc8cd6c",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Meta 回归\"\n---\n\n\n\n\nMeta-regression 通过假设混合效应模型来实现。由于抽样误差和研究之间的异质性，观察到的研究偏离了真实的总体效应。\n\n普通最小二乘法的加权版本\n\nmeta 回归 使用一个或多个变量x来预测真实效应大小的差异。\n\n$$\n\\hat\\theta_k = \\theta + \\beta x_{k} + \\epsilon_k+\\zeta_k\n$$\n\n抽样误差$\\epsilon_k$和研究间异质性 $\\zeta_k$\n\n固定效应（$\\beta$）和 随机效应（$\\zeta_k$）\n\n## Meta回归模型\n\n### **使用分类预测因子的meta回归**\n\n$$\n\\begin{equation}   \nD_g=\\begin{cases}     \n0: & \\text{Subgroup A}\\\\     \n1: & \\text{Subgroup B.}   \n\\end{cases}   \n\\end{equation}\n$$\n\n$$\n\\begin{equation} \\hat\\theta_k = \\theta + \\beta D_g +\\epsilon_k+\\zeta_k.  \\end{equation}\n$$\n\n则\n\n$$\n\\begin{equation}   D_g=\\begin{cases}     0: & \\text{$\\hat\\theta_k = \\theta_A + \\epsilon_k+\\zeta_k$}\\\\     1: & \\text{$\\hat\\theta_k = \\theta_B + \\theta_{\\Delta} +\\epsilon_k+\\zeta_k$}   \\end{cases}   \\end{equation}\n$$\n\n![](images/metaregression_subgroups.png){fig-align=\"center\" width=\"419\"}\n\n### **使用连续预测因子的meta回归**\n\n![](images/metareg_form_continuous.png){fig-align=\"center\" width=\"293\"}\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(meta)\nm.gen <- metagen(TE = TE,\n                 seTE = seTE,\n                 studlab = Author,\n                 data = dmetar::ThirdWave,\n                 sm = \"SMD\",\n                 fixed = FALSE,\n                 random = TRUE,\n                 method.tau = \"REML\",\n                 method.random.ci = \"HK\",\n                 prediction = T,\n                 title = \"Third Wave Psychotherapies\")\nsummary(m.gen)\n#> Review:     Third Wave Psychotherapies\n#> \n#>                           SMD            95%-CI %W(random)\n#> Call et al.            0.7091 [ 0.1979; 1.2203]        5.0\n#> Cavanagh et al.        0.3549 [-0.0300; 0.7397]        6.3\n#> DanitzOrsillo          1.7912 [ 1.1139; 2.4685]        3.8\n#> de Vibe et al.         0.1825 [-0.0484; 0.4133]        7.9\n#> Frazier et al.         0.4219 [ 0.1380; 0.7057]        7.3\n#> Frogeli et al.         0.6300 [ 0.2458; 1.0142]        6.3\n#> Gallego et al.         0.7249 [ 0.2846; 1.1652]        5.7\n#> Hazlett-Stevens & Oren 0.5287 [ 0.1162; 0.9412]        6.0\n#> Hintz et al.           0.2840 [-0.0453; 0.6133]        6.9\n#> Kang et al.            1.2751 [ 0.6142; 1.9360]        3.9\n#> Kuhlmann et al.        0.1036 [-0.2781; 0.4853]        6.3\n#> Lever Taylor et al.    0.3884 [-0.0639; 0.8407]        5.6\n#> Phang et al.           0.5407 [ 0.0619; 1.0196]        5.3\n#> Rasanen et al.         0.4262 [-0.0794; 0.9317]        5.1\n#> Ratanasiripong         0.5154 [-0.1731; 1.2039]        3.7\n#> Shapiro et al.         1.4797 [ 0.8618; 2.0977]        4.2\n#> Song & Lindquist       0.6126 [ 0.1683; 1.0569]        5.7\n#> Warnecke et al.        0.6000 [ 0.1120; 1.0880]        5.2\n#> \n#> Number of studies: k = 18\n#> \n#>                              SMD            95%-CI    t  p-value\n#> Random effects model (HK) 0.5771 [ 0.3782; 0.7760] 6.12 < 0.0001\n#> Prediction interval              [-0.0542; 1.2084]              \n#> \n#> Quantifying heterogeneity (with 95%-CIs):\n#>  tau^2 = 0.0820 [0.0295; 0.3533]; tau = 0.2863 [0.1717; 0.5944]\n#>  I^2 = 62.6% [37.9%; 77.5%]; H = 1.64 [1.27; 2.11]\n#> \n#> Test of heterogeneity:\n#>      Q d.f. p-value\n#>  45.50   17  0.0002\n#> \n#> Details of meta-analysis methods:\n#> - Inverse variance method\n#> - Restricted maximum-likelihood estimator for tau^2\n#> - Q-Profile method for confidence interval of tau^2 and tau\n#> - Calculation of I^2 based on Q\n#> - Hartung-Knapp adjustment for random effects model (df = 17)\n#> - Prediction interval based on t-distribution (df = 17)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nyear <- c(2014, 1998, 2010, 1999, 2005, 2014, \n          2019, 2010, 1982, 2020, 1978, 2001,\n          2018, 2002, 2009, 2011, 2011, 2013)\n\nm.gen.reg <- metareg(m.gen, ~year)\nm.gen.reg\n#> \n#> Mixed-Effects Model (k = 18; tau^2 estimator: REML)\n#> \n#> tau^2 (estimated amount of residual heterogeneity):     0.0188 (SE = 0.0226)\n#> tau (square root of estimated tau^2 value):             0.1371\n#> I^2 (residual heterogeneity / unaccounted variability): 29.26%\n#> H^2 (unaccounted variability / sampling variability):   1.41\n#> R^2 (amount of heterogeneity accounted for):            77.08%\n#> \n#> Test for Residual Heterogeneity:\n#> QE(df = 16) = 27.8273, p-val = 0.0332\n#> \n#> Test of Moderators (coefficient 2):\n#> F(df1 = 1, df2 = 16) = 9.3755, p-val = 0.0075\n#> \n#> Model Results:\n#> \n#>          estimate       se     tval  df    pval     ci.lb     ci.ub     \n#> intrcpt  -36.1546  11.9800  -3.0179  16  0.0082  -61.5510  -10.7582  ** \n#> year       0.0183   0.0060   3.0619  16  0.0075    0.0056    0.0310  ** \n#> \n#> ---\n#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n\n\n\n\n$\\hat\\tau^2_{\\text{unexplained}}=$ 0.0188\n\n$R^2_*$ =77.08% 意味着真实效应大小的 77% 的差异可以用出版年份来解释，这是一个相当大的值。\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbubble(m.gen.reg, studlab = TRUE)\n```\n\n::: {.cell-output-display}\n![](Meta_Regression_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# 通过meta回归进行亚组分析\nmetareg(m.gen, RiskOfBias)\n#> \n#> Mixed-Effects Model (k = 18; tau^2 estimator: REML)\n#> \n#> tau^2 (estimated amount of residual heterogeneity):     0.0691 (SE = 0.0424)\n#> tau (square root of estimated tau^2 value):             0.2630\n#> I^2 (residual heterogeneity / unaccounted variability): 60.58%\n#> H^2 (unaccounted variability / sampling variability):   2.54\n#> R^2 (amount of heterogeneity accounted for):            15.66%\n#> \n#> Test for Residual Heterogeneity:\n#> QE(df = 16) = 39.3084, p-val = 0.0010\n#> \n#> Test of Moderators (coefficient 2):\n#> F(df1 = 1, df2 = 16) = 2.5066, p-val = 0.1329\n#> \n#> Model Results:\n#> \n#>                estimate      se     tval  df    pval    ci.lb   ci.ub      \n#> intrcpt          0.7691  0.1537   5.0022  16  0.0001   0.4431  1.0950  *** \n#> RiskOfBiaslow   -0.2992  0.1890  -1.5832  16  0.1329  -0.6999  0.1014      \n#> \n#> ---\n#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n\n\n\n\nRiskOfBiaslow 效应大小 g = 0.7691-0.2992 ≈0.4699\n\n## **多元回归**\n\n$$\n\\begin{equation} \\hat \\theta_k = \\theta + \\beta_1x_{1k} + ... + \\beta_nx_{nk} + \\epsilon_k + \\zeta_k \\tag{multiple-metareg} \\end{equation}\n$$\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(metafor)\nlibrary(tidyverse)\nlibrary(dmetar)\ndata(MVRegressionData)\nglimpse(MVRegressionData)\n#> Rows: 36\n#> Columns: 6\n#> $ yi         <dbl> 0.09437543, 0.09981923, 0.16931607, 0.17511107, 0.27301641,…\n#> $ sei        <dbl> 0.1959031, 0.1918510, 0.1193179, 0.1161592, 0.1646946, 0.17…\n#> $ reputation <dbl> -11, 0, -11, 4, -10, -9, -8, -8, -8, 0, -5, -5, -4, -4, -3,…\n#> $ quality    <dbl> 6, 9, 5, 9, 2, 10, 6, 3, 10, 3, 1, 5, 10, 2, 1, 2, 4, 1, 8,…\n#> $ pubyear    <dbl> -0.85475360, -0.75277184, -0.66048349, -0.56304843, -0.4308…\n#> $ continent  <fct> 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,…\n```\n:::\n\n\n\n\n### 多重共线性\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nMVRegressionData[,c(\"reputation\", \"quality\", \"pubyear\")] %>% \n    cor()\n#>            reputation    quality    pubyear\n#> reputation  1.0000000  0.3015694  0.3346594\n#> quality     0.3015694  1.0000000 -0.1551123\n#> pubyear     0.3346594 -0.1551123  1.0000000\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nm.qual <- rma(yi = yi,\n              sei = sei,\n              data = MVRegressionData,\n              method = \"ML\",\n              mods = ~ quality,\n              test = \"knha\")\n\nm.qual\n#> \n#> Mixed-Effects Model (k = 36; tau^2 estimator: ML)\n#> \n#> tau^2 (estimated amount of residual heterogeneity):     0.0667 (SE = 0.0275)\n#> tau (square root of estimated tau^2 value):             0.2583\n#> I^2 (residual heterogeneity / unaccounted variability): 60.04%\n#> H^2 (unaccounted variability / sampling variability):   2.50\n#> R^2 (amount of heterogeneity accounted for):            7.37%\n#> \n#> Test for Residual Heterogeneity:\n#> QE(df = 34) = 88.6130, p-val < .0001\n#> \n#> Test of Moderators (coefficient 2):\n#> F(df1 = 1, df2 = 34) = 3.5330, p-val = 0.0688\n#> \n#> Model Results:\n#> \n#>          estimate      se    tval  df    pval    ci.lb   ci.ub    \n#> intrcpt    0.3429  0.1354  2.5318  34  0.0161   0.0677  0.6181  * \n#> quality    0.0356  0.0189  1.8796  34  0.0688  -0.0029  0.0740  . \n#> \n#> ---\n#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nm.qual.rep <- rma(yi = yi, \n                  sei = sei, \n                  data = MVRegressionData, \n                  method = \"ML\", \n                  mods = ~ quality + reputation, \n                  test = \"knha\")\n\nm.qual.rep\n#> \n#> Mixed-Effects Model (k = 36; tau^2 estimator: ML)\n#> \n#> tau^2 (estimated amount of residual heterogeneity):     0.0238 (SE = 0.0161)\n#> tau (square root of estimated tau^2 value):             0.1543\n#> I^2 (residual heterogeneity / unaccounted variability): 34.62%\n#> H^2 (unaccounted variability / sampling variability):   1.53\n#> R^2 (amount of heterogeneity accounted for):            66.95%\n#> \n#> Test for Residual Heterogeneity:\n#> QE(df = 33) = 58.3042, p-val = 0.0042\n#> \n#> Test of Moderators (coefficients 2:3):\n#> F(df1 = 2, df2 = 33) = 12.2476, p-val = 0.0001\n#> \n#> Model Results:\n#> \n#>             estimate      se    tval  df    pval    ci.lb   ci.ub      \n#> intrcpt       0.5005  0.1090  4.5927  33  <.0001   0.2788  0.7222  *** \n#> quality       0.0110  0.0151  0.7312  33  0.4698  -0.0197  0.0417      \n#> reputation    0.0343  0.0075  4.5435  33  <.0001   0.0189  0.0496  *** \n#> \n#> ---\n#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nanova(m.qual, m.qual.rep)\n#> \n#>         df     AIC     BIC    AICc   logLik     LRT   pval      QE  tau^2 \n#> Full     4 19.4816 25.8157 20.7720  -5.7408                58.3042 0.0238 \n#> Reduced  3 36.9808 41.7314 37.7308 -15.4904 19.4992 <.0001 88.6130 0.0667 \n#>              R^2 \n#> Full             \n#> Reduced 64.3197%\n```\n:::\n\n\n\n\n`anova` `LRT` X2= 19.4992 ,p\\<0.001\n\n### 交互效应\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Add factor labels to 'continent'\n# 0 = Europe\n# 1 = North America\nlevels(MVRegressionData$continent) = c(\"Europe\", \"North America\")\n\n# Fit the meta-regression model\nm.qual.rep.int <- rma(yi = yi, \n                      sei = sei, \n                      data = MVRegressionData, \n                      method = \"REML\", \n                      mods = ~ pubyear * continent, \n                      test = \"knha\")\n\nm.qual.rep.int\n#> \n#> Mixed-Effects Model (k = 36; tau^2 estimator: REML)\n#> \n#> tau^2 (estimated amount of residual heterogeneity):     0 (SE = 0.0098)\n#> tau (square root of estimated tau^2 value):             0\n#> I^2 (residual heterogeneity / unaccounted variability): 0.00%\n#> H^2 (unaccounted variability / sampling variability):   1.00\n#> R^2 (amount of heterogeneity accounted for):            100.00%\n#> \n#> Test for Residual Heterogeneity:\n#> QE(df = 32) = 24.8408, p-val = 0.8124\n#> \n#> Test of Moderators (coefficients 2:4):\n#> F(df1 = 3, df2 = 32) = 28.7778, p-val < .0001\n#> \n#> Model Results:\n#> \n#>                                 estimate      se    tval  df    pval    ci.lb \n#> intrcpt                           0.3892  0.0421  9.2472  32  <.0001   0.3035 \n#> pubyear                           0.1683  0.0834  2.0184  32  0.0520  -0.0015 \n#> continentNorth America            0.3986  0.0658  6.0539  32  <.0001   0.2645 \n#> pubyear:continentNorth America    0.6323  0.1271  4.9754  32  <.0001   0.3734 \n#>                                  ci.ub      \n#> intrcpt                         0.4750  *** \n#> pubyear                         0.3380    . \n#> continentNorth America          0.5327  *** \n#> pubyear:continentNorth America  0.8911  *** \n#> \n#> ---\n#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n\n\n\n\n### 过拟合\n\n$R^2_*$ = 100% ，在实践中，几乎不会解释数据中的所有异质性——事实上，如果在现实生活中的数据中找到这样的结果，这可能是模型过度拟合了。\n\n### 排列测试\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npermutest(m.qual.rep)\n#> Running 1000 iterations for an approximate permutation test.\n#> \n#> Test of Moderators (coefficients 2:3):¹\n#> F(df1 = 2, df2 = 33) = 12.2476, p-val = 0.0010\n#> \n#> Model Results:\n#> \n#>             estimate      se    tval  df    pval¹    ci.lb   ci.ub      \n#> intrcpt       0.5005  0.1090  4.5927  33  0.1990    0.2788  0.7222      \n#> quality       0.0110  0.0151  0.7312  33  0.4460   -0.0197  0.0417      \n#> reputation    0.0343  0.0075  4.5435  33  0.0010    0.0189  0.0496  *** \n#> \n#> ---\n#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n#> \n#> 1) p-values based on permutation testing\n```\n:::\n\n\n\n\n### 多模型推理\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmultimodel.inference(TE = \"yi\", \n                     seTE = \"sei\",\n                     data = MVRegressionData,\n                     predictors = c(\"pubyear\", \"quality\", \n                                    \"reputation\", \"continent\"),\n                     interaction = FALSE)\n#> \n  |                                                                            \n  |                                                                      |   0%\n  |                                                                            \n  |====                                                                  |   6%\n  |                                                                            \n  |=========                                                             |  12%\n  |                                                                            \n  |=============                                                         |  19%\n  |                                                                            \n  |==================                                                    |  25%\n  |                                                                            \n  |======================                                                |  31%\n  |                                                                            \n  |==========================                                            |  38%\n  |                                                                            \n  |===============================                                       |  44%\n  |                                                                            \n  |===================================                                   |  50%\n  |                                                                            \n  |=======================================                               |  56%\n  |                                                                            \n  |============================================                          |  62%\n  |                                                                            \n  |================================================                      |  69%\n  |                                                                            \n  |====================================================                  |  75%\n  |                                                                            \n  |=========================================================             |  81%\n  |                                                                            \n  |=============================================================         |  88%\n  |                                                                            \n  |==================================================================    |  94%\n#> \n#> \n#> Multimodel Inference: Final Results\n#> --------------------------\n#> \n#>  - Number of fitted models: 16\n#>  - Full formula: ~ pubyear + quality + reputation + continent\n#>  - Coefficient significance test: knha\n#>  - Interactions modeled: no\n#>  - Evaluation criterion: AICc \n#> \n#> \n#> Best 5 Models\n#> --------------------------\n#> \n#> \n#> Global model call: metafor::rma(yi = TE, sei = seTE, mods = form, data = glm.data, \n#>     method = method, test = test)\n#> ---\n#> Model selection table \n#>    (Intrc) cntnn  pubyr   qulty   rpttn df logLik AICc delta weight\n#> 12       +     + 0.3533         0.02160  5  2.981  6.0  0.00  0.536\n#> 16       +     + 0.4028 0.02210 0.01754  6  4.071  6.8  0.72  0.375\n#> 8        +     + 0.4948 0.03574          5  0.646 10.7  4.67  0.052\n#> 11       +       0.2957         0.02725  4 -1.750 12.8  6.75  0.018\n#> 15       +       0.3547 0.02666 0.02296  5 -0.395 12.8  6.75  0.018\n#> Models ranked by AICc(x) \n#> \n#> \n#> Multimodel Inference Coefficients\n#> --------------------------\n#> \n#> \n#>                          Estimate  Std. Error   z value  Pr(>|z|)\n#> intrcpt                0.38614661 0.106983583 3.6094006 0.0003069\n#> continentNorth America 0.24743836 0.083113174 2.9771256 0.0029096\n#> pubyear                0.37816796 0.083045572 4.5537402 0.0000053\n#> reputation             0.01899347 0.007420427 2.5596198 0.0104787\n#> quality                0.01060060 0.014321158 0.7402055 0.4591753\n#> \n#> \n#> Predictor Importance\n#> --------------------------\n#> \n#> \n#>        model importance\n#> 1    pubyear  0.9988339\n#> 2  continent  0.9621839\n#> 3 reputation  0.9428750\n#> 4    quality  0.4432826\n```\n\n::: {.cell-output-display}\n![](Meta_Regression_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n",
    "supporting": [
      "Meta_Regression_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}